---
title: 'Movelet: Output for Paper'
author: "Virgilio Gonzenbach"
date: "10/7/2021"
output:
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, fig.align = "center",
                      message = FALSE, warning = FALSE,
                      fig.width = 10)
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())
```

```{r load}
library(dplyr)
library(tidyr)
library(ggplot2)
library(ggpubr)
library(ggsci)
library(flextable)
source("Code/functions.R")
source("Code/summary.R")

patients = c(19, 20, 28, 32, 40, 52, 75, 86, 88, 89)
sessions = c(5, 6, 8, 9, 11, 12)
smooth = c(TRUE, FALSE)

df = expand.grid(patients, sessions, smooth)
colnames(df) = c("patient", "session", "smooth")

make_metrics_df = function(df){
  
  # for each patient, ses combination get metrics from confusion matrix + percent_correct at each cut_off
  metrics_df = df %>% apply(1, function(x){
    pred = loadPrediction(patient = x["patient"], ses = x["session"], x["smooth"])
    row = get_metrics(pred$test$Accuracy$table)
    
    percent_correct = mutate(pred$test$Session, percent_correct = correct_med_pred / med_session)$percent_correct
    names(percent_correct) = paste0("correct_at_",pred$test$Session$cut_off)
    row = c(row, percent_correct)
    return(row)
  }) %>% t() %>% as.data.frame()
  
  return(cbind(df, metrics_df))
}

# Prepare smoothing indicator variable for plotting
metrics_df = make_metrics_df(df)
metrics_df$smooth = ifelse(metrics_df$smooth, "Post-Smoothing", "Pre-Smoothing") # Fix name
metrics_df$smooth = factor(metrics_df$smooth, levels=rev(unique(metrics_df$smooth))) # Reverse order
```

## Training 1 med session
### Metrics across patients

```{r boxplot_n1}
metrics_df_long = metrics_df %>% group_by(patient, smooth) %>% select(Accuracy, Precision, F1.score, Sensitivity, Specificity) %>% summarize_all(mean) %>% pivot_longer(-c(patient, smooth), names_to = "Metric")

metrics_df_long %>% ggplot(aes(x=Metric, y = value, color=Metric)) + geom_jitter() + geom_boxplot(alpha=0) + facet_wrap(~smooth) + 
  theme_bw() + ggtitle("Summary metrics for Movelet prediction (1 session training)") + theme(plot.title = element_text(hjust = 0.5)) +
  scale_color_d3()
```

### Metrics across sessions

```{r table_n1, results='asis'}

# Prepare table with smoothing
table1 = metrics_df %>% filter(smooth=="Pre-Smoothing") %>% group_by(session) %>% select(Accuracy, Precision, F1.score, Sensitivity, Specificity) %>% summarize_all(mean)

# Prepare table without smoothing
table2 = metrics_df %>% filter(smooth=="Post-Smoothing") %>% group_by(session) %>% select(Accuracy, Precision, F1.score, Sensitivity, Specificity) %>% summarize_all(mean) %>% as.data.frame()

# Join tables
tables = cbind(table1, table2[, -1]) %>% round(2)
colnames(tables)[2:11] = paste0(colnames(tables)[2:11], rep(c(".T", ".F"), each = 5))
headers = data.frame(col_keys = colnames(tables), 
                     from = c("Session", rep(c("Pre-Smoothing", "Post-Smoothing"), each=5)),
                     names = c("Session", colnames(cbind(table1[-1], table2[, -1])))
                     )
# Print table as flextable
tables %>% flextable::flextable() %>% 
  set_header_df(mapping = headers, key = "col_keys") %>% 
  merge_h(part="header") %>% 
  merge_v(part="header") %>% 
  theme_vanilla() %>% 
  width(width = 27, unit = "in") %>% 
  align(align="center", part="all") %>% 
  vline(part="header")
  
```

## Metrics across training modes

```{r}
# Load data for all training modes
sessions_n2 = combn(sessions, 2) %>% t() %>% apply(1, function(x) paste(x, collapse=","))
sessions_n3 = combn(sessions, 3) %>% t() %>% apply(1, function(x) paste(x, collapse=","))

df = rbind(expand.grid(patients, sessions, smooth), 
           expand.grid(patients, sessions_n2, smooth),
           expand.grid(patients, sessions_n3, smooth))

colnames(df) = c("patient", "session", "smooth")

metrics_df = make_metrics_df(df)

# make n_train dataframe
metrics_df = metrics_df %>% tibble::add_column(n_train = stringr::str_count(metrics_df$session, ",") + 1, .before = "session") 
metrics_df$smooth = ifelse(metrics_df$smooth, "Post-Smoothing", "Pre-Smoothing")
metrics_df$smooth = factor(metrics_df$smooth, levels=rev(unique(metrics_df$smooth))) # Reverse order
```

```{r train_n_boxplot}
metrics_df_long = metrics_df %>% group_by(patient, n_train, smooth) %>% select(Accuracy, Precision, F1.score, Sensitivity, Specificity) %>% summarize_all(mean) %>% pivot_longer(-c(patient, n_train, smooth),  names_to = "Metric")

metrics_df_long %>% ggplot(aes(x=n_train, y = value, color=as.factor(n_train))) + 
  geom_jitter() + facet_grid(smooth~Metric) +  geom_boxplot(alpha=0) + 
  theme_bw() + ggtitle("Summary metrics for Movelet prediction (n session training)") + 
  theme(plot.title = element_text(hjust = 0.5)) + guides(color=guide_legend(title="N trained med sessions")) + xlab("Train N") +
  scale_color_lancet() 
```
